### ISSUE TITLE
[Feat]: Added the Script to AUR for Arch Linux

### ISSUE THREAD

**Issue by niksingh710** [getnf/getnf#46]
I loved the Script.
It is simple and minimal and yet solves a problem I used to face daily.
As of `aur` contains all the nerd fonts packages on its repo but getting a list of the latest one fetched from the nerd font repo was not an option in them.

And installing this script via the installation command was fine for me, but I wanted it to be much easier to install in Arch Linux for my future install.

- [AUR Package](https://aur.archlinux.org/packages/getnf)
## Installation
The user can use any `aur` helper of their choice like `paru` or `yay`
and then install it in their system.

```bash
yay -S getnf
```

If this seems to be a fine addition I can create a `pr` for updated README.

**Comment by ronniedroid** [comment]
Glad you enjoyed using the tool.

Please do make the PR, I love it, thank you

**Comment by niksingh710** [comment]
Created #47
