### ISSUE TITLE
Working with zip is expense for download size, switch to tar

### ISSUE THREAD

**Issue by ronniedroid** [getnf/getnf#50]
We should get the list of fonts from the releases/assets API endpoint as that gives as an easy access to the font download link and download and untar the tar.xz files instead of the zip files. 

Hack.zip 13mb
Hack.tar.xz 2mb

link to API: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest

**Comment by arnavgr** [comment]
Yes that seems really good because we won't need unzip as a dependency since tar is pre-installed on all linux distributions
