### ISSUE TITLE
Update AUR dependencies

### ISSUE THREAD

**Issue by trimclain** [getnf/getnf#52]
Hi @niksingh710, please update the dependencies in the [AUR](https://aur.archlinux.org/packages/getnf). In #51 we switched to using `tar` and don't **require** ncurses anymore.  
See the [README](https://github.com/getnf/getnf?tab=readme-ov-file#dependencies)

**Comment by niksingh710** [comment]
Thanks for notifying.
Updated the dependencies list.

**Comment by trimclain** [comment]
@niksingh710 I don't think you **need** to specify `tar` as a dependency since it's comes with the `base` package. If you don't have `tar`, you don't have Arch Linux.

**Comment by niksingh710** [comment]
yeah, that make sense had added it for edge case but now realized if no `tar` then pacman won't even work.
So would be removing that.
