### ISSUE TITLE
--one-top-level is not supported

### ISSUE THREAD

**Issue by akbo** [getnf/getnf#53]
When trying to download a font, I get the following error message:

```
tar: Option --one-top-level is not supported
```

I'm on MacOS, which uses bsdtar (not gnu tar) as default:

```
% tar --version
bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 
```

It looks like the project switched from zip to tar about an hour ago. Has this been tested on MacOS?

**Comment by trimclain** [comment]
Thanks for reporting the issue. I'll fix it asap

**Comment by akbo** [comment]
9 minutes from bug report to fix. This is insane!! Thanks a lot!
