### ISSUE TITLE
How do I make a pull request without forking this repo?

### ISSUE THREAD

**Issue by arnavgr** [getnf/getnf#54]
I already have a fork of this repo that adds additional functionality for termux, but I can't contribute to this repo since making a PR requires you to fork this repo and GitHub doesn't allow more than 1 fork, is there any workaround this?

**Comment by trimclain** [comment]
You use that same fork and create a new branch for each PR. But make sure your own changes from the termux PR don't sneak in (you commited them to the main branch of your fork)

**Comment by trimclain** [comment]
Also, before making a PR, I would recommend starting with an issue, especially whenever you are planning something big. That way you can make sure your ideas align with ours.

**Comment by arnavgr** [comment]
Ok I will make a seperate issue
