### ISSUE TITLE
feat: system wide installation and check version

### ISSUE THREAD

**Issue by johnr14** [getnf/getnf#58]
Hi, great script !

But it's just missing system wide installation with `-S` for system install.

1) Add a  SYS_DIST_DIR pointing to /usr/local/share/fonts (mac ?) and a SYS_FONT_RELEASES_DIR
2) Use sudo if not root for install and  fc-cache -fv
3) Use SYS_DIST_DIR instead of DIST_DIR for install
4) Use installed_system_fonts as well as installed_user_fonts for listing installed fonts. (add color base on user or system?) (sort results or keep seperated ?)
5) Add -S to getops and help 

Also, it would be nice if the script can check if a new version of itself is available with a `-V` and use `-v` for current version.

If you want to keep `-V` for current name, other options could be `-g` or `-c` for `get|check` getnf latest version...
On version check, `echo " curl https://raw.githubusercontent.com/getnf/getnf/main/getnf > ${0}"` so the user can just paste it to update the script or if interactive it could offer to upgrade the script (but must check file ownership and sudo if necessary).

Thanks

**Comment by johnr14** [comment]
And side note : found out by reading about it at https://linuxtldr.com/install-fonts-on-linux/ after a googling for `install nerd fonts bash script`.

**Comment by ronniedroid** [comment]
Hey, glad you enjoyed using the tool.

is the global install something important? I an not sure what the use case is.

**Comment by johnr14** [comment]
It's if you use more than one user on a computer, prevents installation in all users home dir.
My use case is to have more than one user, like one for work and one for personal use so I don't mix what I'm supposed to do. But could be used if computer is shared between family members also.

**Comment by arnavgr** [comment]
> If you want to keep `-V` for current name, other options could be `-g` or `-c` for `get|check` getnf latest version... On version check, `echo " curl https://raw.githubusercontent.com/getnf/getnf/main/getnf > ${0}"` so the user can just paste it to update the script or if interactive it could offer to upgrade the script (but must check file ownership and sudo if necessary).

i tried implementing something similar in #57 but they said the script should not update itself and they are working on go-version of getnf that will be available in repos
