### ISSUE TITLE
How to install all nerd-fonts?

### ISSUE THREAD

**Issue by niels0n** [getnf/getnf#60]
Hi, I'm trying to install all nerd-fonts. is there a way to do it without specifying every single font name?

**Comment by trimclain** [comment]
You should be able to use the range 1-64 in the menu

**Comment by ronniedroid** [comment]
But why? @niels0n ? 

You know having that many fonts can slow down your system?

**Comment by niels0n** [comment]
I don't think that 67 fonts are really going to make a huge difference on a modern system @ronniedroid. Did you take a look at the size of a single .tff file?

**Comment by ronniedroid** [comment]
> I don't think that 67 fonts are really going to make a huge difference on a modern system @ronniedroid. Did you take a look at the size of a single .tff file?

So i was not worried about the disk space but rather the performance of graphical applications that let you set a font, I did a little search on the internet and no, 67 fonts won't cause a problem.

**Comment by niels0n** [comment]
Yeah, some applications like Inkscape sometimes are slowed down a bit when scrolling through fonts, if they are hundreds.
Thank you for the info though!
