### ISSUE TITLE
List all fonts

### ISSUE THREAD

**Issue by ronniedroid** [getnf/getnf#61]
Add an option (`-L` maybe?) to list all fonts, this was the use doesn't have to go into the menu just to get the font name to use with `-i` and `-u`

**Comment by trimclain** [comment]
How similar to the menu should the list be? In 3 rows or not? With positional numbers or just names?

**Comment by ronniedroid** [comment]
> How similar to the menu should the list be? In 3 rows or not? With positional numbers or just names?

Positional numbers won't be that necessary in my opinion. I am not sure if it needs to be in columns too.
