### ISSUE TITLE
I can't see newly installed IBMPlexMono fonts in my iterm2

### ISSUE THREAD

**Issue by asthetik** [getnf/getnf#62]
I tried IBMPlexMono font and setting the font on iterm2 but couldn't get it to work. 
Same operation I could get JetBrainsMono font.

And then I used brew to install the IBMPlexMono font again and I can get it.
`brew install font-ibm-plex --cask`
<img width="1510" alt="image" src="https://github.com/user-attachments/assets/0617e619-617d-4ff0-a120-b192b7cb3ce2">

<img width="1480" alt="image" src="https://github.com/user-attachments/assets/dd03fb08-83e7-4fa7-944f-bda80c732e87">

**Comment by ronniedroid** [comment]
Try searching for BlexMono

**Comment by asthetik** [comment]
> Try searching for BlexMono

got it, thank you!
