### ISSUE TITLE
Work properly on UBlue systems (Bazzite, Bluefin, etc.)

### ISSUE THREAD

**Issue by ashebanow** [getnf/getnf#63]
UBlue's bluefin-dx comes with a large variety of fonts preinstalled, including the Symbols nerd font in regular and mono varieties.  These fonts are located in the `/usr/local/share/fonts` directory, and the Symbols nerd fonts are in a subdirectory `nerd-fonts`.

`getnf` doesn't detect the fonts installed into this subfolder when using the `-g` option, and it doesn't install new nerd fonts there either. `getnf` should  set `FONT_DIR` to this subdirectory if it exists already and `-g` is specified.

This may apply to related Fedora distributions, both  upstream (silverblue, kinoite, sericea) and in sibllings (bazzite, aurora, etc).

**Comment by trimclain** [comment]
`getnf` lists installed fonts by comparing directory names of all fonts in `FONT_DIR` to the list of nerd fonts you get from running `getnf -L`. If a nerd font is installed into a directory with a different name, it won't be listed anyway. If the nerd font wasn't installed with `getnf`, there will be no info about the version of the font, which can lead to it being updated on `getnf -U`. And in case it was already being managed by a package manager, there would most likely be an issue. This raises the question if it's worth to try and detect/manage nerd fonts installed by other tools.

Can you tell me what the name of the directory with Symbols nerd font on your system is? Is the font being managed by a package manager?

**Comment by ashebanow** [comment]
The subdirectory in question is `/usr/local/share/fonts/nerd-fonts`, thanks.

**Comment by trimclain** [comment]
If your system has Symbols nerd fonts (or any other nerd fonts) installed as raw ttf files in `/usr/local/share/fonts/nerd-fonts`, there's no way for `getnf` to detect/manage them. If you are simply asking for `getnf -g` to install the fonts into `/usr/local/share/fonts/nerd-fonts` subdirectory, if it exists, I'd  need a better explanation on why we would want to do that.
